### ISSUE TITLE
handling of gzip conent encoding needs to be fixed for the new Drakma

### ISSUE THREAD

**Issue by avodonosov** [lokedhs/cl-gdata#1]
I see in auth.lisp you use "Accept-Encoding" . "gzip" and then un-gzip the stream.

With the https://github.com/edicl/drakma/issues/45 Drakma unconditionally un-gzips the stream, so your code needs to be adjusted.

**Comment by lokedhs** [comment]
Interesting. Is Drakma now adding that header itself so that I can
completely remove the header altogether?

**Comment by avodonosov** [comment]
No, Accept-Encoding header is not added automatically, as far as I see from the commit

**Comment by tmccombs** [comment]
Drakma no longer unconditionally un-gzips the stream, as of edicl/drakma#53. Now it will un-gzip (or un-deflate) if the :decode-content option is non-nil. (Actually it will also un-gzip if the response has gzip in the Transfer-Encoding header, but that is pretty rare, and as far as I understand the RFC the transfer encoding should be transparent to the application).

**Comment by avodonosov** [comment]
@tmccombs thanks for this.
